# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='key',
            field=models.CharField(default='abc', max_length=64),
            preserve_default=False,
        ),
    ]
