# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0002_snippet_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='key',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
