# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0003_auto_20170807_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='key',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
